### ISSUE TITLE
Glitch on the Home screen

### ISSUE THREAD

**Issue by noobAIcoder** [ushakrishnan/SearchWithOpenAI#2]
PS C:\Work\Repos\SearchWithOpenAI> streamlit run Home.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.113.60:8501

2023-05-25 21:30:42.109 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "C:\Work\Repos\SearchWithOpenAI\Home.py", line 7, in <module>
    intro_markdown = read_markdown_file("README.md")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\Repos\SearchWithOpenAI\Home.py", line 5, in read_markdown_file
    return Path(markdown_file).read_text()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\pathlib.py", line 1059, in read_text
    return f.read()
           ^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1255.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9f in position 3: character maps to <undefined>

**Comment by ushakrishnan** [comment]
Thank you, I believe this is due to encoding issue for character set.  Changes have been made to Home.py line 5.  This should fix your issue.  This should fix the issue, please let me know if this does not fix your issue. 

`return Path(markdown_file).read_text(encoding='utf-8', errors='ignore')`
